export const queryKeys = {
  menuCategories: ['menu-categories'] as const,
  menuItems: ['menu-items'] as const,
  menuItemsByCategory: (id: string) => ['menu-items', 'category', id] as const,
  tables: ['tables'] as const,
  orders: ['orders'] as const,
  ordersByStatus: (s: string) => ['orders', 'status', s] as const,
  kitchenOrders: ['kitchen-orders'] as const,
  tableSessions: ['table-sessions'] as const,
  activeTableSession: (tableId: string) => ['table-sessions', tableId] as const,
  workflows: ['workflows'] as const,
  workflow: (id: string) => ['workflows', id] as const,
  workflowForEntity: (type: string, id: string) => ['workflows', type, id] as const,
  products: ['products'] as const,
  invoices: ['invoices'] as const,
  bookings: ['bookings'] as const,
  rooms: ['rooms'] as const,
  roomTypes: ['room-types'] as const,
  housekeeping: ['housekeeping'] as const,
  maintenance: ['maintenance'] as const,
  suppliers: ['suppliers'] as const,
  purchaseOrders: ['purchase-orders'] as const,
  fonepayQR: ['fonepay-qr'] as const,
  fonepayVerify: ['fonepay-verify'] as const,
  creditCustomers: ['credit-customers'] as const,
  activeOrderByTable: (tableId: string) => ['active-order', tableId] as const,
  roomMappings: ['room-mappings'] as const,
  syncLogs: ['sync-logs'] as const,
  syncLog: (id: string) => ['sync-log', id] as const,
  syncQueue: ['sync-queue'] as const,
  externalBookings: ['external-bookings'] as const,
  externalBooking: (id: string) => ['external-booking', id] as const,
};
